version: '3'

services:
  nginx-rtmp:
    image: tiangolo/nginx-rtmp
    ports:
      - "1935:1935"
      - "8080:8080"
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf
      - /mnt/hls:/mnt/hls
    environment:
      - SERVER_IP=$(curl -s http://ipinfo.io/ip)
    restart: always

  web-server:
    image: nginx
    volumes:
      - ./web:/usr/share/nginx/html
    ports:
      - "80:80"
    restart: always
