version: '3'

services:
  nginx-rtmp:
    image: tiangolo/nginx-rtmp
    ports:
      - "1935:1935" # RTMP 端口
      - "8080:8080" # HLS 流的 HTTP 端口
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf # 映射自定义 Nginx RTMP 配置
      - /mnt/hls:/mnt/hls # 映射 HLS 目录
    restart: always

  web-server:
    image: nginx
    volumes:
      - ./web:/usr/share/nginx/html # web 目录包含您的 HTML 文件
    ports:
      - "80:80" # Web 服务器端口
    restart: always
